services:
  superlink:
    image: flwr/superlink:1.22.0
    command:
      - --insecure
      - --isolation
      - process
    ports:
      - 9092:9092
      - 9093:9093
    networks:
      cellular_lan:
        ipv4_address: 192.168.10.4

  superexec-serverapp:
    build:
      context: ../../flwr-application
      dockerfile_inline: |
        FROM flwr/superexec:1.22.0

        WORKDIR /app
        COPY --chown=app:app pyproject.toml .
        RUN sed -i '/"flwr",/d' pyproject.toml \
          && python -m pip install -U --no-cache-dir .     
        
        ENTRYPOINT ["flower-superexec"]
    command:
      - --insecure
      - --plugin-type
      - serverapp
      - --appio-api-address
      - superlink:9091
    depends_on:
        - superlink
    volumes:
      - ${HOME}/flwr_output/:/app/flwr_output
      - ${HOME}/.ssh:/home/app/.ssh:ro
    networks:
      cellular_lan:
        ipv4_address: 192.168.10.5

  # Test container
  network_tools:
    build:
      dockerfile_inline: |
          FROM ubuntu:22.04
          RUN apt-get update && apt-get install -y net-tools iputils-ping
          ENTRYPOINT [ "/bin/bash", "-c", "sleep infinity" ]
    volumes:
      - ${HOME}/.ssh:/home/.ssh:ro
    networks:
      cellular_lan:
        ipv4_address: 192.168.10.6

networks:
    cellular_lan:
      driver: macvlan
      driver_opts:
        parent: enp1s0
      ipam:
        config:
          - subnet: 192.168.10.0/24
            gateway: 192.168.10.3