name: Client App Docker Build Process

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: fl-client:latest
          load: true

      - name: Test Docker Image
        run: | 
          docker run --rm fl-client:latest python -c "from federated_application.models import ModelWrapper; print('Model imports work!')"
