[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "5GFed"
version = "1.0.0"
description = "Federated Learning with RpI and 5G; Collaborative research with NU and ANL"
license = "Apache-2.0"
dependencies = [
    "flwr",
    "flwr-datasets",
    "torch",
    "torchvision",
    "wandb",
    "pyserial",
    "paramiko",
    "scp"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "Robert Hayek, NU, ANL"

[tool.flwr.app.components]
serverapp = "federated_application.server:app"
clientapp = "federated_application.client:app"

[tool.flwr.app.config]
rounds = 1
fraction_evaluate = 0
epochs = 1
learning_rate = 0.001
batch_size = 128
momentum = 0.9
weight_decay = 0.000001
min_num_clients = 1
interface = 'Ethernet'
model = 'squeezenet1_1'
dataset = 'cifar10'
distribution = 'iid'
wandb_api_key = ''
enable_server_wandb = false
enable_client_wandb = false
debug = true

[tool.flwr.federations.lan-deployment]
address = "129.105.6.252:9093"
insecure = true

[tool.flwr.federations.wlan-deployment]
address = "10.106.4.27:9093"
insecure = true

[tool.flwr.federations.wwan-deployment]
address = "192.168.10.4:9093"
insecure = true

[tool.flwr.federations.local-deployment]
address = "127.0.0.1:9093"
insecure = true