[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "5GFed"
version = "1.0.0"
description = "Federated Learning with RpI and 5G; Collaborative research with NU and ANL"
license = "Apache-2.0"
dependencies = [
    "flwr",
    "flwr-datasets",
    "torch",
    "torchvision",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "Robert Hayek, NU, ANL"

[tool.flwr.app.components]
serverapp = "federated_application.server:app"
clientapp = "federated_application.client:app"

[tool.flwr.app.config]
rounds = 10
fraction_evaluate = 1
local_epochs = 3
learning-rate = 0.01
batch_size = 16
min_num_clients = 3

[tool.flwr.federations]
default = "federated_application"

[tool.flwr.federations.federated_application]
address = "192.168.70.129:9093"
insecure = true
