name: Build FL Client Docker Image

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-client:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: fl-client
      dockerfile_path: ./docker/client/Dockerfile