name: Build FL Server Docker Image

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-server:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: fl-server
      dockerfile_path: ./docker/server/Dockerfile